osx_image: xcode8.3
language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: Sabbath Shool.xcworkspace
xcode_scheme: Sabbath School
before_install:
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp ss_certs_travis ~/.ssh/
- chmod 600 ~/.ssh/ss_certs_travis
- cp ss_ssh_config_travis ~/.ssh/config
- bundle install
- bundle exec pod install --repo-update
script:
- bundle exec fastlane travis
env:
  global:
  - secure: WqJH63Xq3sqlIKkr2iFOprI/m7EZudrdLT8MPN3/TaNcIkttG6UanXGlkV5Wu+l/aRPo1i1gykgJu3x33O1wsip0Fj/iR99hoGiwQ1dN37vm46jNxBuQZr5aflXLHUp6KErw4MpAIKsyMQhQ3VIPXzH+FNDV84ozZ7EVwzPtLjB8jMEWUDRoJx7k3Twqr9Fsj0G+I75IDxWHyFnu093rVsLKkCUvUGY30GkRgoJWr0lKZYsNCVD6VTXmcTY6IZHrCWIshhLsyxPPreVIZCeXJcbSE8XI2IxTbXXU7Zg+2qIQYL8KbjppBQeU2KDGxYpHgtYfOWuuz/3oUB6bVFkv/KyEzC0dlu7l56yYDLzu64gtMCN4xhec0MIYl948ttBGXV3yW5llP21Eqg6cBaqhjzE9ymcEOMta0t9N7sc/kqzpbufQZdnmHwbQXDrFysuNH3JxC4crkCd449qxkm7+xSJFkj15IT+IwmAx8f++roTuzGveK9C900kXgl/zBk70LZBDqhHSGyLBHHr8LO1ny0t1719Nqcv3TXHCkEWmnCVylQrQHFL9W7LQ4NFD4GWZXQvCgzOBnlpvprvPtQDoK9xguLn28qoarrPX/hhIoyCxulxRp86El6hB9YO0+A3kX4wrN7ULXAdLGG1ctvdeZlgUBxTUDqXftDF3wmr1hKY=
  - secure: Byu0bEIysSNudaabWFxpgaoYmVS0coWOZeyeowmjtYWLra/L92RxCoCn4QbsOEprsKk2YpHId6X4LX8wrIfhoBpSopWapy3P8bFjxUQcmFMYgd8LlJ2mS9RF7USBnrTTBU7vh2fxxOThoTEDxU/4+pERoNc/0NLGrcgV0V+rDXOvSIavCM5xkpBoU1wCjb8ISOewBMa2Eu47jJFoDMf0Hijf91RWWlvyEaXb+bJ/s0Atl5A2fjh22ulsHIYOYs4etX3w7CBeqivtpKJczE8e+IivN+o0WJIw8LG/M5tZ1yFDO1MST4JUDWzyVPdJgckWlJBuiy6c+LAMKcP5Jsi1FX06WRIhXQc9Q160sqIzRnLLZBpRc7bCd0AycbtMGLA1DhIiMcaYP0ynXKsuxSu3oEvpSAVFmlcEMn1JXmBuTi9GYC/tK0dqIO08+kYTfMGdhZfFas3Fa4R5ud+9wRXLhTUkGa+J+njRovrurpetLTGOeV+QeYqOIz9VoeW76yBWubwQlvN+LrRz6dMlGHfbKwrpDLzgfZvRvTkGlz8oHYe+Zb9MQBvt766YXRULpQKa24J6IcSsTdilDQFbjpUTuI0knia59KTBNeIieYR3Fk/2WMh3DKY+lTvKH6Om0aL8xjk6UvGYxe3EWuFhUOw0FkcraNIlC0taCODxfDGcPHY=
  - secure: eBF47/uI2ZTkqtBfeg5WZMwY05PMhc/qZbuyL43ScCV7UOdNhUZx2ULjAum7EEH7GNQ/M+4yIbvMbJx7rHzdYRPPxRYvV1pjpOkBPKmDpB8pymDYTFdsNuYiPI7D4/e/DyV50oVOk8p+cvH1P2kAtLZHg7LDid9KsXpBrWl3qjgyOXT3Gq/zYr3w2kddHyjnsAFUF1BAnV6KyPg16z/tba8Y82z0pWhoJhcxa3Mht9nspoNX1LoYzQ1N2RV6o2xNxkC2qdgYnRjjbHx1VBQdZgOjWCX3zUWdY5jjp0wSxNU4bGrnEoqxN2ZiyLJM6cHwJsLg2vS2wR93DVjtilgw4PRahdB8uanwm1DVkbG2n883FpYpLipWDzjtfGEy29FEw84Tf/ipb6zr6p9cykWYKABQCRyXJjE0/dkR/YV53Xb/wIwPxdkBvdLmxa30tsY7NYDHOKcLrhhiaE7efjNoYAann5pUC5Q2cr0/ql09IuO5Da6CsgQjyP5QGDgYLMtjGL6GyrQfR1Ud9RjZfQIU6gKjgzBsh0QA/WEf3LW+e0hdlbXlmOIkYgILBNXRVAmCu3VPXOE685wuv9vlCUIh7CJDLJ93TYeDDaDb7otEh4OO11fZG8QOPjSADLn12skKLUEAQsDAkClFAwbhBUx9FqWm2pe8ZjDWpwULSDAGezM=
