osx_image: xcode8.3
language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: Sabbath Shool.xcworkspace
xcode_scheme: Sabbath School
before_install:
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in ss_certs_travis.enc -out ss_certs_travis -d
- cp ss_certs_travis ~/.ssh/
- chmod 600 ~/.ssh/ss_certs_travis
- cp ss_ssh_config_travis ~/.ssh/config
- bundle install
- bundle exec pod install --repo-update
script:
- bundle exec fastlane travis
env:
  global:
  - secure: e/yPUMwwmUDXyJ6CzQqEkpPUeoGt8Zk2iGDk+8fJWw4PSmLDR8dVrRg5O6f+zVglVlQjmnhNAt1AGXz+r5xIHmtG5uNrUpQJn1qMyRK9vjmOXufEcmZtlr4VJAkKIhObc6rovBqyaK2ULNKmQT2nFA6uPo/endHW3bg5tGN2uNm0Bxy1Un1pUOg0ALstfmqJZ7wtSIeN/7KTEValWabheKMHPSlZLQJL3o9bU4rR69Of6jMjZDIHAw8rehB68/pLGYcRCKUklg4vv/EfqOwydQiI7srt1DVZ/RWV/wQtGzqN+3TlgRgJqo5zWoxQLJcYWxsYu7EBiLKTEfa5ghbiOerahKe2I6arEWUc3O9XlngZFbSgflLo5BMRhNPy+6P4Pf7GdLfGRO9gj0Ng8HBitG7dt2mq2L45nXUPGLgj4jebkUkOJ17TAu3qLE0GqcPznFHDNZhd8zpdLuntACDq9HatamxGkPtSYGmRYr4OJgXaEYFuaBOMWx8WuuYqZxloD1/uVUAwccGqJB+AH68SQaCDBtgB1zw2Wa5imbx8xmktSVqPPPx9RGOq9MQNs5M+rlTTc1dMYCnpCLWqv3S7uGqVelD6r7gIhHNufvE7zqUfN8VE/VFA903fZ4BSK99IjXrf3xeZ/h9GEaQmnFbcu4T+oWP+c8lkDc276Sjp8L4=
  - secure: WqJH63Xq3sqlIKkr2iFOprI/m7EZudrdLT8MPN3/TaNcIkttG6UanXGlkV5Wu+l/aRPo1i1gykgJu3x33O1wsip0Fj/iR99hoGiwQ1dN37vm46jNxBuQZr5aflXLHUp6KErw4MpAIKsyMQhQ3VIPXzH+FNDV84ozZ7EVwzPtLjB8jMEWUDRoJx7k3Twqr9Fsj0G+I75IDxWHyFnu093rVsLKkCUvUGY30GkRgoJWr0lKZYsNCVD6VTXmcTY6IZHrCWIshhLsyxPPreVIZCeXJcbSE8XI2IxTbXXU7Zg+2qIQYL8KbjppBQeU2KDGxYpHgtYfOWuuz/3oUB6bVFkv/KyEzC0dlu7l56yYDLzu64gtMCN4xhec0MIYl948ttBGXV3yW5llP21Eqg6cBaqhjzE9ymcEOMta0t9N7sc/kqzpbufQZdnmHwbQXDrFysuNH3JxC4crkCd449qxkm7+xSJFkj15IT+IwmAx8f++roTuzGveK9C900kXgl/zBk70LZBDqhHSGyLBHHr8LO1ny0t1719Nqcv3TXHCkEWmnCVylQrQHFL9W7LQ4NFD4GWZXQvCgzOBnlpvprvPtQDoK9xguLn28qoarrPX/hhIoyCxulxRp86El6hB9YO0+A3kX4wrN7ULXAdLGG1ctvdeZlgUBxTUDqXftDF3wmr1hKY=
  - secure: uDXYGGUB7kN8mZh8CCr/qA5hp+5p1cc/42CzsB/8E0vqn0HZYd33BK/FixFgb2jKHZZuvj8l29hBOORgGHleUSeBa4HGmOT74NnfSIxqoH2C+jiIKXhsNE/CYjAH0azcvIAX6OED1KsXN5b4rZwJk6bYDmhyigL+rRReUKIiwM838e0dTzA+MYmZHP5N4TZl3Exhb5FVhkBZYUDIfzNPWNg7Monzk3vp7XhqCPs1prIPZv/zExQBzXakFv9iUZ6XCtzZ1WPuH/PYWSnuI+EFwYOyHPw9Bh+3az8wGjN9wYbn+3VSfjI1sxjMWjEi4En5iW47BXC8eiRXe+TXJG0oIfeKi1KcnAsbLgtdGmxf+FrUs4fpNEG9/l5+xCi7WL15ys/fAEaIOiCVKozFH40NyGIUXu01bwurtQ4jWjaGf61NhsozSHAYF9dkyxX7tFIRI6QtcjzDI4XvOWIwY+v4XZm8DhLQ2IwK4NxsFdJIBcBo0HEAkauCi+VLPUmRxRHdbL0UgxOWwojYKuOjUHlm+9cfWjqbkZxoLfiti3h33LInfr4cL6+AaDP5EXs213YG6a3vvvACvGtIsIERs2BySskNkP4wCwZ4OsCFqtNiGyK167dSGA7Iy6OKzv0NhjMt1dQThtFJ7gkMqY/tNj6TNKCXWKiSaU4+mibo1/Oq4s0=
