osx_image: xcode8.3
language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: Sabbath Shool.xcworkspace
xcode_scheme: Sabbath School
before_install:
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- cp ss_certs_travis ~/.ssh/
- chmod 600 ~/.ssh/ss_certs_travis
- cp ss_ssh_config_travis ~/.ssh/config
- bundle install
- bundle exec pod install --repo-update
script:
- bundle exec fastlane travis
env:
  global:
  - secure: Gu3JoYeEa0n6JU6W6mU9J4SUyEOYZtGgQn3SmGHsYOiue/VsjswWUM7AsYixcLUCcZFwcb3esHu3JvAaQKc/fZy6bbqVE1fyG4Ny/pUerwzm9hh3sGDekVrQs50x/wJo28D6O1jmod15k2/FAwMuGvBurrlj6adC0cWxyPFJaRHrGQXQdpLvy5F041TPIt0rzP9F1qdpDTlC66ibIicv2mhvSvqaJP4asDF7s9M/Kb34LBLsRzZoZCZ0/L6f5LGrC2QLjPB0FJ4Om6dElPYKcZZPHAWidnxonokJocbT0mwQVQfdId8t1n8+BPiYtj/UbqHp/B2gjrAR/YwGPUhZ+p99YIdkWbOHfzi01SNkXjYE3GddbiGF7MBvr5ZT+PqVm0I40iSNM/RhqIzd3sjNjFdHPemlhw4F4FdRkUHGZgijVQ14P/3Zad8kI8pr+R1kkAC8JtWyQV9ru9l2iErqtYSnp/DbFrg1IT3g5DQRtUCoQn1Z0TA9MrgiMO7L5lcVLz25UoT6VsvQXJGPObKKHVXgwxDTsdvQbYCcmsGk1zfS2UOB22A6vxJwwOtTnKAgfLcLydfGG7x5lTcLakk71ykPikHrxiu0ybH2s63IhLiqfelnRQXsrKMqhXjAH6zgzLHTr5EumjA+6fjH2wYivZztjXKpQLa1C7jsLmPx4K0=
  - secure: iKHsp66AC0QaeHxwP5YKA3JePlW0jrffxeYCE6ReX7PQsAtuj67AeU7N3+EPk6yQvxseK4Wgd6Ti6mpN1QE61xdoNlzhP+MUVy3ncuqIePIrHT+HGIPqvg/tUZNiSG/62mgeMIch1btn08GRo+ak8Px0OMSNt/lEswP26I1azG91SSUM/P/gUR2Q9qazEXLYmnOArGjjj6AfPFcd2WOAtSp8zRPhu4shHOCDzJjWrtdApYW9GlrAnRjKG5zT/wI9QvDhHjiWVwWeMv1+CU3NVMgDFWbyVNPfOk9Oa+uUy5YHRIRM79sdXYdZykPQNS62Rwo01V5iAZwq3sxKlO1nPDgumIQ2uA7neKAFvL/5yvd1ibCKO73TqJMkJEFW4hVgVGu5eqyPjHSlE5zJw4jUgR2i5b/DNHT7fHGTa60ln7aoBtvNmsoqmbVYVeeE8zCKkeD6dEHluyOu6WzWhkyJMDwsE8DR48/XcJZf7Mtxn0kg9Sdm+K+dyqStOMdb6TvPls2TK5shVOMOPGjLgRkXW95+piHTr+N0lg8VG/DKdcdPJBeR9gaCnUISYT2qjNvUHlpxzmbTLY1wHG7OQq9ZkPFiznPoBHAVcpO4VrdJyVHkUpV55CwVmKeXhX/gTRexPK9tmTTuz0/VUA+9CE3/bXbBV6mZJ+cfP/QZ5NGsbEA=
global:
  secure: OYiNeNJMWdEjjNx98F691djPC/eRrEORzZZ5fXTE3wcKRLzr7HJk40AlaBRkxxaMlc4h71EASJC56p5E344AvrZzBlRYvvemj95+Cf4zvcY1ZDkYVv0GABTHpkTaw35GnzSVmiUl/9lJadJuakrY4Le50gXSKg1r/A95EBq49Z0dxPmIQ1BNcBNEKtOP3ED1WFKJOOhDUCusM2DO0wuj1YTe0MBTINL9Khhku5F6DYAHHDNTtXp2VO7xv3EM5x+PElMnjChbYgzW4xJA8nSYnTMZNeybKTqLo84iggivK8VXB0fl8ldwMb7Qji8RI7+Mc97+004V49Tbw1i0Dd8sLnwU9s5cODyuIw5HVc5BNwEI5lZsQzeq76j3ae9CEJfQeyFYal/Xs5uKj1z16qdQR13z257W6zSQrkIMeidOgAnYrT+HhmUjkXgpSN8KELA4vkV96uDxy1wiY8x/08uRM52P17zkyyXfauNSotbpx1YfDgraRpYPzynHjjp1s+tFy0PJAkK9NPTsnFsed9ZIqJH6qgcjEilRNCUJZbvSKjlVdUWqoqjSt3VJgdv++4bGrz2Tro83FP4tdvl63V8NBEXbSMReWvKNBb3DMykEtg4CTs0XcOXf1OwEpbPLS2DMAJMYPOkGIpvejQghg9lG15Y2RxKU0a8msruyJUOyupo=
