osx_image: xcode8.3
language: objective-c
cache:
- bundler
- cocoapods
xcode_workspace: Sabbath Shool.xcworkspace
xcode_scheme: Sabbath School
before_install:
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in Fabric.buildSecret.enc -out Sabbath\ School/Resources/Fabric.buildSecret -d
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in Fabric.apiKey.enc -out Sabbath\ School/Resources/Fabric.apiKey -d
- openssl aes-256-cbc -K $encrypted_142095b63e54_key -iv $encrypted_142095b63e54_iv
  -in ss_certs_travis.enc -out ss_certs_travis -d
- cp ss_certs_travis ~/.ssh/
- chmod 600 ~/.ssh/ss_certs_travis
- cp ss_ssh_config_travis ~/.ssh/config
- bundle install
- bundle exec pod install --repo-update
script:
- bundle exec fastlane travis
env:
  global:
  - secure: e/yPUMwwmUDXyJ6CzQqEkpPUeoGt8Zk2iGDk+8fJWw4PSmLDR8dVrRg5O6f+zVglVlQjmnhNAt1AGXz+r5xIHmtG5uNrUpQJn1qMyRK9vjmOXufEcmZtlr4VJAkKIhObc6rovBqyaK2ULNKmQT2nFA6uPo/endHW3bg5tGN2uNm0Bxy1Un1pUOg0ALstfmqJZ7wtSIeN/7KTEValWabheKMHPSlZLQJL3o9bU4rR69Of6jMjZDIHAw8rehB68/pLGYcRCKUklg4vv/EfqOwydQiI7srt1DVZ/RWV/wQtGzqN+3TlgRgJqo5zWoxQLJcYWxsYu7EBiLKTEfa5ghbiOerahKe2I6arEWUc3O9XlngZFbSgflLo5BMRhNPy+6P4Pf7GdLfGRO9gj0Ng8HBitG7dt2mq2L45nXUPGLgj4jebkUkOJ17TAu3qLE0GqcPznFHDNZhd8zpdLuntACDq9HatamxGkPtSYGmRYr4OJgXaEYFuaBOMWx8WuuYqZxloD1/uVUAwccGqJB+AH68SQaCDBtgB1zw2Wa5imbx8xmktSVqPPPx9RGOq9MQNs5M+rlTTc1dMYCnpCLWqv3S7uGqVelD6r7gIhHNufvE7zqUfN8VE/VFA903fZ4BSK99IjXrf3xeZ/h9GEaQmnFbcu4T+oWP+c8lkDc276Sjp8L4=
  - secure: WqJH63Xq3sqlIKkr2iFOprI/m7EZudrdLT8MPN3/TaNcIkttG6UanXGlkV5Wu+l/aRPo1i1gykgJu3x33O1wsip0Fj/iR99hoGiwQ1dN37vm46jNxBuQZr5aflXLHUp6KErw4MpAIKsyMQhQ3VIPXzH+FNDV84ozZ7EVwzPtLjB8jMEWUDRoJx7k3Twqr9Fsj0G+I75IDxWHyFnu093rVsLKkCUvUGY30GkRgoJWr0lKZYsNCVD6VTXmcTY6IZHrCWIshhLsyxPPreVIZCeXJcbSE8XI2IxTbXXU7Zg+2qIQYL8KbjppBQeU2KDGxYpHgtYfOWuuz/3oUB6bVFkv/KyEzC0dlu7l56yYDLzu64gtMCN4xhec0MIYl948ttBGXV3yW5llP21Eqg6cBaqhjzE9ymcEOMta0t9N7sc/kqzpbufQZdnmHwbQXDrFysuNH3JxC4crkCd449qxkm7+xSJFkj15IT+IwmAx8f++roTuzGveK9C900kXgl/zBk70LZBDqhHSGyLBHHr8LO1ny0t1719Nqcv3TXHCkEWmnCVylQrQHFL9W7LQ4NFD4GWZXQvCgzOBnlpvprvPtQDoK9xguLn28qoarrPX/hhIoyCxulxRp86El6hB9YO0+A3kX4wrN7ULXAdLGG1ctvdeZlgUBxTUDqXftDF3wmr1hKY=
  - secure: Byu0bEIysSNudaabWFxpgaoYmVS0coWOZeyeowmjtYWLra/L92RxCoCn4QbsOEprsKk2YpHId6X4LX8wrIfhoBpSopWapy3P8bFjxUQcmFMYgd8LlJ2mS9RF7USBnrTTBU7vh2fxxOThoTEDxU/4+pERoNc/0NLGrcgV0V+rDXOvSIavCM5xkpBoU1wCjb8ISOewBMa2Eu47jJFoDMf0Hijf91RWWlvyEaXb+bJ/s0Atl5A2fjh22ulsHIYOYs4etX3w7CBeqivtpKJczE8e+IivN+o0WJIw8LG/M5tZ1yFDO1MST4JUDWzyVPdJgckWlJBuiy6c+LAMKcP5Jsi1FX06WRIhXQc9Q160sqIzRnLLZBpRc7bCd0AycbtMGLA1DhIiMcaYP0ynXKsuxSu3oEvpSAVFmlcEMn1JXmBuTi9GYC/tK0dqIO08+kYTfMGdhZfFas3Fa4R5ud+9wRXLhTUkGa+J+njRovrurpetLTGOeV+QeYqOIz9VoeW76yBWubwQlvN+LrRz6dMlGHfbKwrpDLzgfZvRvTkGlz8oHYe+Zb9MQBvt766YXRULpQKa24J6IcSsTdilDQFbjpUTuI0knia59KTBNeIieYR3Fk/2WMh3DKY+lTvKH6Om0aL8xjk6UvGYxe3EWuFhUOw0FkcraNIlC0taCODxfDGcPHY=
